### PR TITLE
Data Loaders

### PR DESCRIPTION
**Pull request by mumichae**
Integrate a data loader for multiple anndata datasets. Provides datasets for all tasks.

### CODE REVIEW

**Comment by rcannood** [comment]
Thanks @mumichae! I'll wait for CI to finish before accepting the PR.

**Comment by rcannood** [comment]
Then again, if TI fails, it's not your fault :) Let's merge!

**Comment by LuckyMD** [comment]
I'm thinking "oh, 16 changed files... that will take some time"... and then it's a find and replace main -> common ;). 

This generic data loader doesn't allow you to specify obs covariate yet. Might be good to standardize that for batch integration, no? I.e. for pancreas:

`adata.obs['batch'] = adata.obs['tech']` or sth like this?

**Comment by mumichae** [comment]
Yes, the idea was to have a general data loader and then modify the data according to task. I'm basically trying to follow the openproblems repo structure

**Pull request merged**
